# Generated by Django 4.2.6 on 2023-10-10 19:59

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Demande',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name', models.CharField(max_length=200)),
                ('last_name', models.CharField(max_length=200)),
                ('Email', models.CharField(max_length=200)),
                ('address', models.CharField(max_length=200)),
                ('postcode', models.CharField(max_length=200)),
                ('location', models.CharField(max_length=200)),
                ('brand', models.CharField(max_length=200)),
                ('model', models.CharField(max_length=200)),
                ('vehicle_type', models.CharField(max_length=200)),
                ('fuel', models.CharField(max_length=200)),
                ('gear_type', models.CharField(max_length=200)),
                ('last_MFK', models.CharField(max_length=200)),
                ('performance', models.CharField(max_length=200)),
                ('mileage', models.CharField(max_length=200)),
                ('initial_registration', models.CharField(max_length=200)),
                ('color', models.CharField(max_length=200)),
                ('message', models.CharField(max_length=200)),
                ('asking_price', models.CharField(max_length=200)),
                ('Displacement', models.CharField(max_length=200)),
                ('doors', models.CharField(max_length=200)),
            ],
        ),
    ]
