# Generated by Django 4.1.2 on 2023-10-11 16:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='demande',
            name='mobile',
            field=models.CharField(default='123', max_length=100),
        ),
    ]
