# Generated by Django 4.2.3 on 2023-10-13 13:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0002_demande_mobile'),
    ]

    operations = [
        migrations.AlterField(
            model_name='demande',
            name='Email',
            field=models.EmailField(max_length=254),
        ),
    ]
