# Generated by Django 4.1.2 on 2023-10-14 01:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0002_demande_mobile'),
    ]

    operations = [
        migrations.AddField(
            model_name='demande',
            name='image1',
            field=models.ImageField(default='pics_default/br1.png', upload_to='photos/%y/%m/%d'),
        ),
        migrations.AddField(
            model_name='demande',
            name='image2',
            field=models.ImageField(default='pics_default/br1.png', upload_to='photos/%y/%m/%d'),
        ),
        migrations.AddField(
            model_name='demande',
            name='image3',
            field=models.ImageField(default='pics_default/br1.png', upload_to='photos/%y/%m/%d'),
        ),
        migrations.AddField(
            model_name='demande',
            name='image4',
            field=models.ImageField(default='pics_default/br1.png', upload_to='photos/%y/%m/%d'),
        ),
    ]
