# Generated by Django 4.1.2 on 2023-10-14 01:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0003_demande_image1_demande_image2_demande_image3_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='demande',
            name='Email',
            field=models.EmailField(max_length=254),
        ),
        migrations.AlterField(
            model_name='demande',
            name='image1',
            field=models.ImageField(upload_to='photos/%y/%m/%d'),
        ),
        migrations.AlterField(
            model_name='demande',
            name='image2',
            field=models.ImageField(upload_to='photos/%y/%m/%d'),
        ),
        migrations.AlterField(
            model_name='demande',
            name='image3',
            field=models.ImageField(upload_to='photos/%y/%m/%d'),
        ),
        migrations.AlterField(
            model_name='demande',
            name='image4',
            field=models.ImageField(upload_to='photos/%y/%m/%d'),
        ),
        migrations.AlterField(
            model_name='demande',
            name='mobile',
            field=models.CharField(max_length=200),
        ),
    ]
