# Generated by Django 4.1.2 on 2023-10-14 01:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0005_alter_demande_image1_alter_demande_image2_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='demande',
            name='image1',
            field=models.ImageField(blank=True, null=True, upload_to='photos/'),
        ),
        migrations.AlterField(
            model_name='demande',
            name='image2',
            field=models.ImageField(blank=True, null=True, upload_to='photos/'),
        ),
        migrations.AlterField(
            model_name='demande',
            name='image3',
            field=models.ImageField(blank=True, null=True, upload_to='photos/'),
        ),
        migrations.AlterField(
            model_name='demande',
            name='image4',
            field=models.ImageField(blank=True, null=True, upload_to='photos/'),
        ),
    ]
