# Generated by Django 4.1.2 on 2023-10-15 05:05

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0003_alter_demande_email'),
        ('website', '0006_alter_demande_image1_alter_demande_image2_and_more'),
    ]

    operations = [
    ]
