# Generated by Django 4.2.6 on 2023-10-18 03:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0007_merge_20231014_2053'),
    ]

    operations = [
        migrations.AlterField(
            model_name='demande',
            name='mobile',
            field=models.CharField(default='123', max_length=100),
        ),
    ]
