# Generated by Django 4.1.2 on 2023-10-22 04:18

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0007_merge_20231014_2105'),
        ('website', '0008_alter_demande_mobile'),
    ]

    operations = [
    ]
